<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE PERIODICO [
    <!ELEMENT PERIODICO (ARTICULO+)>
    <!ELEMENT ARTICULO (TITULAR,SUBTITULO,ENTRADA,CUERPO)>
    <!ELEMENT TITULAR (#PCDATA)>
    <!ELEMENT SUBTITULO (#PCDATA)>
    <!ELEMENT ENTRADA (#PCDATA)>
    <!ELEMENT CUERPO (#PCDATA)>
    <!ATTLIST ARTICULO AUTOR CDATA #REQUIRED>
    <!ATTLIST ARTICULO EDITOR CDATA #IMPLIED>
    <!ATTLIST ARTICULO FECHA CDATA #IMPLIED>
    <!ATTLIST ARTICULO EDICION CDATA #IMPLIED>
    <!ENTITY PERIODICO "Vervet Logic Times">
    <!ENTITY EDITOR "Vervet Logic Press">
    <!ENTITY COPYRIGHT "Copyright 1998 Vervet Logic Press">
]>

<PERIODICO>
    <ARTICULO AUTOR="Manuel Sanchez" EDITOR="EDITOR" FECHA="13/04/2024" EDICION="Manuel Sanchez">
        <TITULAR>Descubrimiento arqueologico</TITULAR>
        <SUBTITULO>Hallan una tumba faraonica intacta en el Valle de los Reyes</SUBTITULO>
        <ENTRADA> Arqueólogos egipcios han hecho un descubrimiento asombroso en el Valle de los Reyes: una tumba faraónica que ha permanecido intacta durante miles de años. El hallazgo promete revelar nuevos secretos sobre la vida y la cultura del antiguo Egipto.</ENTRADA>
        <CUERPO>La tumba, identificada como KV65, fue encontrada por un equipo de excavación en una zona poco explorada del valle. Los investigadores creen que pertenece a un alto funcionario del período ramésida, debido a los relieves y jeroglíficos encontrados en las paredes interiores. Se espera que el descubrimiento arroje luz sobre la vida cotidiana, las creencias religiosas y las prácticas funerarias de la élite egipcia de esa época</CUERPO>    
    </ARTICULO>
    <ARTICULO AUTOR="Federico Martin" EDITOR="EDITOR" FECHA="13/04/2024" EDICION="Federico Martin">
        <TITULAR>Avance cientifico en la licha contra el cancer</TITULAR>
        <SUBTITULO>Nuevo tratamiento experimental muestra resultados prometedores</SUBTITULO>
        <ENTRADA>Un equipo de investigadores ha desarrollado un tratamiento experimental que podría revolucionar la forma en que se combate el cáncer. Los primeros ensayos clínicos han arrojado resultados prometedores, ofreciendo esperanza a millones de pacientes en todo el mundo.</ENTRADA>
        <CUERPO>El tratamiento, basado en la terapia génica y la inmunoterapia, se dirige a las células cancerosas de manera más precisa y efectiva que los métodos tradicionales. En los ensayos iniciales, se observó una reducción significativa en el tamaño de los tumores y una mejora en la supervivencia de los pacientes tratados. Si los resultados se confirman en ensayos posteriores, este tratamiento podría convertirse en una herramienta invaluable en la lucha contra el cáncer.</CUERPO>
    </ARTICULO>
    <ARTICULO AUTOR="Monica Solera" EDITOR="EDITOR" FECHA="13/04/2024" EDICION="Monica Solera">
        <TITULAR>Crisis humanitaria en la frontera sur</TITULAR>
        <SUBTITULO>Aumenta el flujo de refugiados en busca de seguridad y protección</SUBTITULO>
        <ENTRADA>La situación en la frontera sur ha alcanzado un punto crítico, con un aumento alarmante en el número de personas que huyen de la violencia y la persecución en sus países de origen. Organizaciones humanitarias advierten sobre una crisis inminente si no se toman medidas urgentes para abordar esta situación.</ENTRADA>
        <CUERPO>Miles de refugiados, incluidas familias enteras y niños no acompañados, han llegado a la frontera en busca de seguridad y protección. Sin embargo, la capacidad de los centros de recepción y las agencias de ayuda está al límite, lo que dificulta proporcionar asistencia adecuada a quienes la necesitan. Se requiere una respuesta coordinada a nivel nacional e internacional para garantizar la protección de los derechos humanos y la dignidad de los refugiados en esta situación desesperada.</CUERPO>
    </ARTICULO>
</PERIODICO>